variable_ids:
  # - hfds
  - rsdo
  - umo
  - vmo
  - mlotst
  - so
  - thetao
  - uo
  - vo
  - wfo
  - tos
member_ids:
  - r1i1p2f1
  # - r3i1p2f1
experiment_ids:
  hist-1950:
    - 1950
    - 2015
  highres-future:
    - 2015
    - 2050
lats:
  - -32
  - -0
lons:
  - 130
  - 170
levs:
  - 0
  - 20
processing:
  do_regrid: true
  do_delete_og: false
  do_crop: true
